### ISSUE TITLE
Editor Button script disables multiple object editing for all scripts

### ISSUE THREAD

**Issue by Domukas** [miguel12345/EditorButton#2]
As this editor override default editor for all scripts, it doesn't support multi-object editing out of the box. Correct way would be to add [CanEditMultipleObjects] attribute to EditorButton editor and handle multiple object usage correctness in GUI.

**Comment by miguel12345** [comment]
Hi, thank you for the feedback! This issue has been fixed in the latest commit. Please let me know if it works out for you
